- _sass/_base.scss
Modified _base.scss in order to tell webkit not to automatically scale font sizes. I noticed that if I browsed my page on my iPhone, the font size of the footer would start at 12pt, then get scaled up (to ~20pt) as I rotated my phone to landscape, and not scale back to 12pt when I rotated back to landscape. A similar thing was happening on some p-tags, though with different sizes. It turns out that there is a text-size-adjust css property which is used to automatically scale up fonts on mobile devices, ignoring the css (the idea being to improve usability on older sites which didn't design for mobile). As the site is designed for mobile, we don't want any automated scaling to be applied, so I set -webkit-text-size-adjust: 100% in order to prevent the scaling from occurring. This fixes …
> Fixed webkit text scaling `bug`

- bin/deploy
The step in the deploy script that deletes almost all files except for _site/ was causing issues if you have a custom domain name. GitHub pages requires a CNAME, so I added this to the list of files not to delete.
> Do not delete CNAME file 

- _layouts/bib.html
There currently is a bug when generating the author field for single-author publications: an "and" is added in front of the name of the author (as in the demo, where we have "and Einstein, Albert", see [here](https://alshedivat.github.io/al-folio/publications/)).
This PR fixes it with with some minimal changes in `_layouts/bib.html`.
> Fixes bug when generating publications from single authors.

- _sass/_base.scss
- _sass/_header.scss
Fixed issue #26, as explained [here](https://css-tricks.com/elegant-fix-jumping-scrollbar-issue/). I've added an overall left margin to the main html tag, so that margin:auto works as if the scrollbar is invisible. Since the header has a fixed position, I've also changed the left position of the header. The horizontal alignment of the header now doesn't change between 'short' and 'long' pages.
The other way to fix this would be to make the vertical scrollbar always appear, regardless of whether or not the content requires it. This would achieve the same visual consistency, but I think is much less aesthetically pleasing.
> Added css to take account of vertical scroll bar and avoid content jumps

- _includes/social.html
This pull proposes hiding the social email button altogether if `site.email` is falsy.
> Make the display of an email conditional

- README.md
- _config.yml
- _includes/head.html
This commit adds support for serving Open Graph meta tags inside the HTML head. When enabled, links to the page on social media will display a preview.
NB: twitter behaves somewhat differently and may require twitter card meta tags in addition to Open Graph.
https://ogp.me/
Draft for now: Works nicely on skype. The twitter validator likes it, but I failed to make it work inside a tweet. Need to also test a couple more sites/apps. Success/failure reports welcome!
> Enable preview images on social media

- _config.yml
I love the new design, but was confused why the blog link didn't show up on the nav bar.  It was because the blog needs a name for it to appear.  Just added a comment in the config that documents this behavior.  
Thank you for a great template!
> Document that blog_name changes the navbar

- _config.yml
- _includes/header.html
- _layouts/about.html
If more than 2 elements in _config.yml variable title, any middle names or initials will be displayed.
This doesn't handle things like a Jr. or III yet.  The lastname variable will always catch the last thing.  
An alternative would be adding  either
- a separate variable in _config.yml for name suffix.  
- Or perhaps revamp all this with separate config variables explicitly set for Personal name, Middle names, Family name, Suffix
> changes allow for more than first and last name to be displayed.  

- _layouts/about.html
Added back the missing description on `about.html`, similar to `page.html`. This could additionally be added back to the `post.html` template as well.
> Adding back the description on the About page.

- _config.yml
- _layouts/bib.html
added a list `scholar: first_name` in `_config.yml`
updated `_layouts/bib.html` template
supports more accurate author annotation by both matching the last name and one form of first name in the `_config.yml/scholar: first_name`
possible related issue #100
> Support more accurate author annotation

- .github/workflows/deploy.yml
- bin/deploy
This will automatically deploy the page when pushing to source branch (i.e. `master` and `source`).
That basically allows editing through the GitHub web interface, no more need to install bundler locally.
This also supports pull requests, which can be useful to collaboratively make a conference page. For PRs the whole build is still done except the actual `git push` at the end. To achieve this I added a `--dry-run` option to `bin/deploy`.
Side notes:
- added `--verbose` option to make debugging of `bin/deploy` easier
- changed the exit code for unknown options to 1, before it would end gracefully (`exit 0`)
- fixed `--user` option calling `shift` twice
- using actions/cache to cache bundle
- the current branch is always used as the source branch, however the deploy action is only …
> Github action: add deploy workflow

- README.md
- _data/coauthors.yml
- _layouts/bib.html
@gkthiruvathukal , I have added coauthor annotation using your suggested `flat` format. Since the author name parsing from bibtex is handled by upstream jekyll-scholar, only first name and last name is processed here. 
The code is not very elegant, but since the code is only used to generate static web pages, it might be okay for now. 
And @alshedivat ,  do you have any suggestions?
We can have more discussion on the implementation here. 
Related issue #100
> add coauthor annotation

- _includes/head.html
- _includes/scripts/misc.html
- _layouts/default.html
* dark_mode.js was not being loaded on distill blog pages.
* Moved dark_mode.js and jquery.html to head.html to simplify/standardize dark mode/theming for other pages.
> Issue 180 - Distill Bugfix

- _config.yml
- _includes/footer.html
Mainly to help with EU GDPR rules.
> add support for impressum page

- _includes/head.html
- _includes/header.html
- _layouts/about.html
The If statements to decide the page title and header seemed incorrect. This fixes these.
> Fix titles and headings

- _includes/head.html
`gitcdn.link` was quite slow, so I tried the alternate link at `gitcdn.xyz` and there are no issues with lag anymore.
`gitcdn` was used to quickly get pygments code highlighting css themes inside `_includes/head.html` from [this](https://github.com/jwarby/jekyll-pygments-themes) repo.
> Change gitcdn link in 

- README.md
When you fork this directory in your local fork, if you remove images from assets, the README file will be broken.
This should fix the README problem, ensuring that images are always up-to-date from the assets folder of the original al-folio folder.
> Fix for images

- .github/workflows/deploy.yml
- README.md
This PR is for https://github.com/alshedivat/al-folio/issues/342 and makes the following changes:
1. Always push the generated website code to `gh-pages`.
2. Update the documentation for the personal/organization webpages.
> Use master for the source code for personal/organization webpages

- Gemfile
- _config.yml
- robots.txt
- Adds support for sitemap using [jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap).
- Adds a robots.txt file.
> Adds support for sitemap and robots.txt

- _config.yml
Fixes #357.
The problem stems from [the default `bibtex_filters`](https://github.com/inukshuk/jekyll-scholar#configuration) applied by `jekyll-scholar` to each field of each bib entry. Since al-folio uses mathjax, these filters are unnecessary.
Also, bump up the MathJAX version to 3.2.0.
> Fix latex rendering issue in the bibliography entries

- CONTRIBUTING.md
- LICENSE
- README.md
Love the template, thanks for all the great work! While browsing the project I noticed some outdated details and proposed some updates:
- CONTRIBUTING: Referred to the [Discussions](https://github.com/alshedivat/al-folio/discussions) forum instead of gitter for general questions (see #210)
- LICENSE: Bumped year to 2021
Also, I took the opportunity to add my website to the list of websites in README.
> minor updates to CONTRIBUTING and LICENSE, add website

- .github/workflows/deploy.yml
The 'main' branch is used in newer GitHub repositories. So I've added it to the trigger list of deploy.yml.
> Add 'main' branch for newer GitHub repositories

- .github/workflows/deploy.yml
- Gemfile
- README.md
- _config.yml
- _includes/projects.html
- _includes/projects_horizontal.html
- _includes/social.html
- _layouts/bib.html
- _news/announcement_2.md
- _pages/about.md
- _pages/projects.md
- _posts/2015-03-15-formatting-and-links.md
- _posts/2015-10-20-math.md
- _posts/2018-12-22-distill.md
- _posts/2020-09-28-github-metadata.md
- _posts/2020-09-28-twitter.md
- _projects/1_project.md
- _projects/2_project.md
- _projects/3_project.md
- _projects/4_project.md
- _projects/5_project.md
- _projects/6_project.md
pull request for issue #408 
This is also working perfectly on my own [website](https://pourmand1376.github.io/).
> add jekyll target blank plugin

- _includes/head.html
- _includes/scripts/analytics.html
- _includes/scripts/footer.html
- _includes/scripts/misc.html
- _layouts/default.html
Hi, 
As it is more efficient in term of loadtime speed, I placed the Javascript files after the body tag. 
Google search console is also showing promising results (15 percent better).
Before the test Google search console was showing **39%** for mobile, and after that, we are getting **54%**. Still, a long way to optimize it completely.
> Optimize Website Load Time

- _config.yml
- _sass/_base.scss
- _sass/_themes.scss
- _sass/_variables.scss
Note: I also changed the `footer_fixed` configuration, which probably shouldn't be merged.
> Optimize dark theme

- blog/index.html
Previously the `read_time` shown in blogs page is broken and always shows 2 minutes. This is due to the wrong variable name in `blog/index.html`. Simply changing `page` to `post` would fix it.
> Fix broken read_time in blog/index.html

- _layouts/distill.html
- _sass/_distill.scss
- assets/js/distillpub/overrides.js
Ensure that jquerry is imported before `js/distillpub/overrides.js`.
> Fix distill dark mode again

- _includes/metadata.html
So for the open graph preview, the metadata.html file is currently displaying `site.title` which is "blank" instead of `title` which is a variable that's created in lines 16-20, which sets the title to the name from the config.yml file, which is what should be used instead. So this change should fix the issue, I've tested it for my wesbite and it works. You can test the issue yourself using https://www.opengraph.xyz/
> fixed title for og preview, otherwise its "blank"

- _sass/_base.scss
As per https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-transition, webkit-transition feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes.
changed "webkit-transition" to "transition-property" in _base.scss
> minor changes

- _posts/2022-02-01-redirect.md
- blog/index.html
Now user can use `redirect` in the blogs to redirect to assets like pdf. I also add an example post to demonstrate how this works.
This is an attempt to solve the issue #534.
> enable blog to redirect to asset

- _layouts/bib.html
For bibtex entries that are neither articles nor proceedings, the value `entrytype` carries over from the previous entry in the loop, leading to incorrect displays. This PR fixes that.
> Empty entrytype if not article or inproceedings

- Gemfile
- _config.yml
- _plugins/external-posts.rb
- _sass/_base.scss
- blog/index.html
Fixes #246.
adds support for displaying links to blog posts from arbitrary external sources on the blog page.
> Add support for external blog posts

- README.md
I did not find the custom bibtex keywords documented anywhere, so I've added them to the main readme under a details tag.
> Added documentation on publication buttons

- _config.yml
- _layouts/bib.html
- _plugins/hideCustomBibtex.rb
Added a plugin to filter irrelevant bibtex keywords in the bib output turned on by `bibtex_show`. The `filtered_keywords` setting in the config decides which keywords to filter out, and I've added all keywords used internally by the webpage as default.
Fixes #547
> Added a plugin to filter irrelevant bibtex keywords from bib output

- _config.yml
- _includes/news.html
> Adds vertical scrollbar to news

- bin/deploy
GitHub Pages automatically tries to process Jekyll site for every deployment. But since, we precompile our Jekyll using GitHub Actions, therefore it will not be required to be processed by GitHub pages. We just need GitHub Pages to deploy the `gh-pages` branch as a static site.
More information: https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
> Adds support for bypassing GitHub Pages Jekyll processing

- _config.yml
- _sass/_base.scss
- blog/index.html
> Adds support for tag-list

- _layouts/about.html
profile image on the about page had typos in the class names, which are fixed in this PR.
> Fix typos in _layouts/about.html

- _config.yml
- _includes/scripts/bootstrap.html
Bootstrap bundle include popperjs.
References:
- https://getbootstrap.com/docs/5.2/getting-started/introduction/#cdn-links
- https://www.jsdelivr.com/package/npm/bootstrap (Looks like the bundle is used more often than the separate scripts)
> Include bootstrap bundle to replace popperjs

- _config.yml
- _includes/scripts/analytics.html
Seems like GA4 analytics uses the same scripts as previous Google Analytics. 
Therefore, I don't think we need to make any more changes. Just added a note in the `_config.yml` and changed the ID to `G-XXXXXXXXXX` to make it clearer.
As Google will [stop supporting previous Universal Analytics](https://support.google.com/analytics/answer/11583528?hl=en&ref_topic=10094551), I did not mention it in code.
> Adds support for GA4 analytics

- _layouts/bib.html
Until now, only publications of type `inproceedings` have the `booktitle` attribute shown, although `incollection` would benefit from it as well.
> Display booktitle for publications of type incollection.

- README.md
I just added a TOC to `readme.md` file. I hope you like it!
> Adding Table of Contents to Readme file

- _config.yml
- _includes/metadata.html
- _includes/social.html
This PR addresses issue #313 according to the suggestion by @alshedivat 
In my tests with my local build, the icon got pulled automatically from the Semantic Scholar site.
> Add Semantic Scholar social integration

- _config.yml
- _includes/metadata.html
- _includes/social.html
#877 is an explanation of the issue. The new icons include Kaggle, LastFM, Spotify, Pinterest, Unsplash, Instagram, and Facebook, and you can change their order.
> add more social media

- README.md
- _config.yml
- _layouts/bib.html
Multiple last names can be defined to be highlighted in the bibliography (#904)
> add multiple last names in bibliography

- README.md
As raised in #399, the info available on the `README.md` does not reflect the current state, this PR should fix that
This was mentioned in  #399
> Improve info about theme colors

- _sass/_base.scss
As reported in #927, the style of the profile class only considers a left-margin regardless of the alignment option selected.
Thus, when the user changes the default alignment there is no corresponding margin to match their selection.
My commit addresses this by enabling the corresponding margin for the left or right alignment options
> Set the margin according to the alignment selected

- _includes/metadata.html
Fixed missing year in title when visualizing blog archive filtered by year
> Fixed missing year in title when in blog archive

- _layouts/post.html
- blog/index.html
Fixes links to jekyll-archive pages when tag/category contains spaces.
> Slugify tag and category links

- README.md
Updated README.md with the correct link to the distill-style blog post example.
> Fixed broken link to distill-style blog post

- _config.yml
- _includes/header.html
- _includes/scripts/progressBar.html
- _layouts/default.html
- _layouts/distill.html
- _sass/_base.scss
This feature adds a horizontal bar under the top menu which tracks the vertical scroll position. Such a feature can be useful to represent how much is left to read on the current page more aesthetically.
As this is an optional feature, `enable_progressbar` must be set to `true` in `_config.yml` to activate the functionality.
I am not the original author of this code. I just made it compatible with the current version of the template at the time of this commit. The original code was most likely authored by Pankaj Parashar in this [post](https://css-tricks.com/reading-position-indicator/) made a few years before the first inclusion in an `al-folio` site. Then, the code was adapted for compatibility with the template at Anthony Plantanios' site. Finally, I did
the last updates to have the …
> Add a progress bar to show the scroll position

- README.md
- _bibliography/papers.bib
- _config.yml
- _layouts/bib.html
[Altmetric](https://www.altmetric.com/) tracks social media and citation activity for a paper. I added an option to add the altmeric id to a paper's bib entry, which results in the altmeric badge for the paper being displayed next to the other buttons. As an example, I added the altmetric id for the Einstein, Podolsky & Rosen paper.
> Add altmetric badges to paper

- README.md
- bin/docker_build_image.sh
- bin/docker_run.sh
- bin/dockerhub_run.sh
- docker-compose.yml
- docker-local.yml
This file makes it easier for windows users to use docker. (Closes #829)
Previous to this commit, those who used Windows had to install Ubuntu inside windows (via WSL) and run our commands. Now they can run it by just typing `docker-compose up`. 
> The main problem was that `./bin/dockerhub_run.sh` command was written with `Bash` in mind and you had to change it a little bit to make it compatible with windows `Powershell`. We shouldn't have two scripts. This is why adding a `docker-compose.yml` file is necessary.
> Add Docker-compose file for windows compatibility 

- _layouts/distill.html
- _layouts/post.html
> Add support for Disqus comments on distill posts

- .github/workflows/deploy.yml
Hi there
First of all, thanks for this amazing complete theme
Due to this warning which has been recently showed by Github, `::set-output` will be deprecated and must be replaced with a new method
topic: [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Thanks
> New update to GH Actions: Deprecating `save-state` and `set-output` commands

- _config.yml
- _includes/metadata.html
- _includes/social.html
Hi, I realized Telegram is not present among the social integrations yet, I added a `telegram_username` entry and accordingly edited `social.html` and `metadata.html` and it correctly works on my side.
Anyway, thanks for the great work with this theme!
> Adds Telegram to social integrations

- README.md
The old explanation was for the old days. Now it can be done much easier. The build command is not necessary for docker-compose, it automatically creates the image if no image exists. 
Output would be like this:
> ADD More Clear Explanations in README

- _includes/repository/repo.html
The current code doesn't handle the repository link when a custom branch is linked. This change allows to display the main repository with a link to the specific branch provided by the user in `_data/repositories.yml`, e.g., `<username>/<repo-name>/tree/<branch>`.
> Adapt repo code to handle branches too

- _config.yml
- _includes/disqus.html
- _includes/giscus.html
- _layouts/distill.html
- _layouts/post.html
- _posts/2015-10-20-disqus-comments.md
- _posts/2018-12-22-distill.md
- _posts/2022-02-01-redirect.md
- _posts/2022-12-10-giscus-comments.md
- assets/js/theme.js
adds support for comments on posts using https://giscus.app/
> Add support for giscus comments

- _posts/2018-12-22-distill.md
resolves #1023.
shows how to embed an interactive plotly chart using iframe (as suggested in #523 workaround).
how it looks:
> Add interactive plotly example to distill post

- assets/js/common.js
The problem with the previous code is that whenever a box (especially abstract) is open, it is difficult to see that the other one (in the case, Bib) becomes open when one clicks on the related button.
> Hide the other opened box (Bib, Abs), if any

- .pre-commit-config.yaml
It is nice to have some pre-commit hooks for checking of spelling and things like this. If you want to see more information take a look at [here](https://calmcode.io/pre-commit/the-problem.html).
Notice that I have just created one file called `.pre-commit-config.yaml` and run `pre-commit install` and then created a commit. All other files are staged automatically for changes. 
There is also a [bot in github marketplace](https://github.com/marketplace/pre-commit-ci) which takes care of this pre-commit hooks in every pull request. So, we do not need to check for spelling errors and formatting styles. However, I can not install it to this repo, the owner himself should install it. To see an example of how it works take a look at one of my PRs at …
> Add Pre-commit Hook

- Dockerfile
- docker-compose.yml
- docker-local.yml
Resolves #1052. I want to get rid of `jekyll` base docker image as it doesn't update regularly and clearly some packages do not support it. 
It gives this error when trying to build website using docker:
```
Liquid Exception: invalid byte sequence in US-ASCII in /srv/jekyll/_layouts/about.html
al-folio-local-website | bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
al-folio-local-website | /var/lib/gems/3.0.0/gems/bibtex-ruby-6.0.0/lib/bibtex/lexer.rb:220:in `scan_until': invalid byte sequence in US-ASCII (ArgumentError)
```
Also this warning comes up when installing jekyll:
```
unable to convert "\xDB" from ASCII-8BIT to UTF-8 for lib/google/protobuf/descriptor_pb.rb, skipping       
=> => # unknown encoding name "chunked\r\n\r\n25" for …
```
> Fix Docker Problem

- _includes/head.html
Since, a image file will always contain a dot and a three letter extension at least (ex: `.jpg`, `.png`, `.jpeg`, etc). Therefore we can safely set the limit up to 4.
fixes #1096
> Update favicon emoji length limit

- _sass/_distill.scss
Make distill hyperlink color logic consistent with rest of the theme.
fixes #1105
> fix distill hyperlink color

- _layouts/bib.html
This makes sure that the image is resized per media type by imagemagick. The result is still a bit too big (1400 width on desktop), but better than nothing.
> Use figure for bib entry preview

- README.md
created a new row in the 'Workshops' section to add a workshop at Cogsci 2022 where we used this awesome template!
Thanks!
> Add CogSci workshop to list of workshops in README

- _config.yml
- _includes/social.html
> Add OSF to social

- README.md
- _config.yml
- _includes/repository/repo_trophies.html
- _pages/repositories.md
Basically, created a new section with your [user trophies](https://github.com/ryo-ma/github-profile-trophy#about-rank) under `repositories`, that looks like this:
It only displays the github user above when there is more than one.
Since there is room for [a lot of customization](https://github.com/ryo-ma/github-profile-trophy#optional-request-parameters) in the trophies, I decided to set some defaults. I set to only display trophies that are above than C level and used some margins that just felt right.
Also, I was shocked to see how many trophies @alshedivat has 🏆.
> Added github 🏆 section in repositories

- .github/workflows/deploy-docker-tag.yml
- .github/workflows/deploy-image.yml
- .github/workflows/deploy.yml
- README.md
**This PR updates `deploy.yml` to use the GitHub Action [Deploy to GitHub Pages](https://github.com/marketplace/actions/deploy-to-github-pages).**
Currently, `deploy.yml` uses the deploy script `bin/deploy` to build and deploy the site. 
This script has worked well so far, but:
- (from experience!) is harder to read, and thus, customize;
- is another non-core script for maintainers to upkeep.
This Action replicates the default behavior of the deploy script: it clears the `gh-pages` branch, then pushes the contents of `_site` to it.
- Replace `bin/deploy` with [Deploy to GitHub Pages](https://github.com/marketplace/actions/deploy-to-github-pages) Action.
- Create build step (`bundle exec jekyll build`) in `deploy.yml`.
- Enable deploy workflow to be manually triggered.
- _(Minor)_ Bump …
> Replace bin/deploy with GitHub Action

- _includes/metadata.html
Basically avoiding a warning that appears when opening the site on Google Chrome
> Avoiding specific warning on Google Chrome

- README.md
- _news/announcement_1.md
- _news/announcement_2.md
- _news/announcement_3.md
Added `related_posts: false` to the announcements front matter to avoid errors like #1203. Also included explanation in README FAQ section.
> Added related_posts false to the announcements front matter

- _layouts/bib.html
Added more options to altmetric badge, changed to arxiv code first to avoid error with doi
> Added more options to altmetric badge, changed to arxiv code first

- README.md
Moved information about using this template to the beginning of the installation part, added a few more documentation links in it, fixed some typos.
> Moved information about creating your repo to front

- _config.yml
Double-star globbing is not allowed:
https://jekyllrb.com/docs/configuration/front-matter-defaults/#glob-patterns-in-front-matter-defaults.
> Fix assets sitemap exclusion

- _config.yml
- _includes/latest_posts.html
- _includes/news.html
- _layouts/about.html
- _pages/about.md
> Implemented latest posts on about page

- _plugins/details.rb
- _posts/2018-12-22-distill.md
- _sass/_distill.scss
> Implemented details tag for distill blog 

- _config.yml
- _includes/metadata.html
- _includes/social.html
> Scopus integration

- blog/index.html
When blog title and description are empty, go from this
to this
> Removed blog header-bar when title and description are empty

- _includes/selected_papers.html
- _pages/publications.md
The bibliography filename `papers.bib` is hard coded in templates, and the equivalent setting in `_config.yml` is not used anywhere. So changing the bib filename in `_config.yml` won't have any effects.
This PR replaces hard-coded filenames with the value from `_config.yml`.
> Fixed hard-coded bib files in templates

- _includes/scripts/misc.html
- _posts/2023-03-21-tables.md
- _sass/_base.scss
- _sass/_themes.scss
- assets/js/common.js
- assets/js/no_defer.js
- assets/js/theme.js
- assets/json/table_data.json
Added support for [Bootstrap Table](https://bootstrap-table.com/). Haven't checked the impact on website loading, but I believe [this kind of table](https://examples.bootstrap-table.com/#welcomes/from-data.html) is way more useful for blog posts and projects pages.
> Added support for Bootstrap table

- _config.yml
- _includes/head.html
- _includes/scripts/misc.html
- _sass/_base.scss
- assets/js/no_defer.js
Fix table color when dark mode is default.
> Fix table color

- _posts/2023-05-12-custom-blockquotes.md
- _sass/_base.scss
- _sass/_themes.scss
Added some custom blockquotes `tip`, `warning`, and `danger` as seen in [jekyll-gitbook](https://sighingnow.github.io/jekyll-gitbook/jekyll/2022-06-30-tips_warnings_dangers.html), and a blog post showcasing them.
Light look:
Dark look:
> Custom blockquotes

- _includes/cv/map.html
- _sass/_base.scss
- assets/js/theme.js
When the dark mode is default, or if you set the page to dark mode and then refresh, the content in "General Information" can't be seen.
This PR fixes the problem.
> Fixes "General Information" section of CV in dark mode.

- _includes/latest_posts.html
- blog/index.html
Fixes #1450, and the behavior of the site with this "new" code is shown in the Expected behavior screenshots there.
I copy-pasted the redirect logic from `blog/index.html` into `_includes/latest_posts.html`, with minor name changes.
I also cleaned up a line in `blog/index.html`.
> Make latest post redirect if the blog post redirects

- _config.yml
- _sass/_base.scss
- blog/index.html
Added the functionality to display categories on the front page of the blog, just like tags.
> add functionality to display categories, like tags, in blog home page

- Gemfile
- _config.yml
- _includes/resume/awards.html
- _includes/resume/basics.html
- _includes/resume/certificates.html
- _includes/resume/education.html
- _includes/resume/interests.html
- _includes/resume/languages.html
- _includes/resume/projects.html
- _includes/resume/publications.html
- _includes/resume/references.html
- _includes/resume/skills.html
- _includes/resume/volunteer.html
- _includes/resume/work.html
- _layouts/cv.html
- assets/json/resume.json
Just as discussed in #1513 , this pull request adds support for [jsonresume](https://jsonresume.org/). Create the resume once, either as a file in the repository or at [github gist](https://gist.github.com/) called `resume.json`. Put the file in the `_config.yaml`  file and that's it! Other platforms like [resumake](https://latexresu.me/) use the same schema.
I also incorperated the changes introduced by #1339 to the best of my abilites. The style could be further improved.
**Please merge this pull request after #1339 is merged, due to dependencies from it**
If someone has a bettet approach on how to solve the problem that each section needs its own template, please let me know. But for now it works fine and is still backwards compatible with the `cv.yaml` file.
> Add jsonresume support

- _layouts/cv.html
The layout template of cv.html has repeated parts. When site.data.resume is not defined, the cv page will be rendered incorrectly.
> Remove repeated layout template of cv.html

- _config.yml
#1569  Fixed mismatch between zotero-id in _config.yml and the zotero-id called upon in the socials html file introduced by #1572 (sorry about that; slipped in when I had to reset my zotero-branch)
> Zotero ID Bugfix

- .github/workflows/deploy-docker-tag.yml
I should merge this whenever normal deploy is well-tested for Mac computers.
> Update Tag Deploys to Support M1 Macbooks

- _plugins/hideCustomBibtex.rb
This fix in https://github.com/alshedivat/al-folio/pull/1429 is not perfect.
`input = input.gsub(/^.*#{keyword}.*$\n/, '')` will fail but return true for cases like looking for "code" from "coder"
The following is the real fix
`input = input.gsub(/^.*\b#{keyword}\b *= *\{.*$\n/, '')`
The `\b` in the regex expression is a word boundary. This means it will not match substrings in other words.
The ` *= *\{` will ensure that the keyword is a field name because bib should follows `<field name> = {<value>}`.
> Fix regex to limit keyword scope to fields

- _layouts/cv.html
- _pages/cv.md
Addressing #1551 using the same sidebar as in #1366, removing the inline ToC menu from the CV
> Moved ToC Menu to Sidebar

- _sass/_base.scss
This addresses https://github.com/alshedivat/al-folio/issues/1425.
Contributions:
- Added border attribute to `.table-dark` within `_base.scss` to override bootstrap theme border settings for `.tabled-bordered`. Displays top border in dark mode for only those tables that are bordered
> Fixing bootstrap dark-table top border

- _config.yml
- _includes/head.html
- _includes/scripts/bootstrap.html
Fixes #1774 by reverting mdb usage to cdn. Weirdly enough, when using from local file it triggers a ripple effect when using `btn` class. It states in the [official docs](https://mdbootstrap.com/docs/standard/methods/ripple/) that:
> By default, ripple is added to every button (via .btn class)
Using [this solution](https://mdbootstrap.com/support/standard/disable-waves-ripple-effect/) only make this flicking happens faster. Also this does seem to be [an issue](https://mdbootstrap.com/support/standard/how-to-disable-ripple-effect/) still in the [latest version](https://github.com/mdbootstrap/mdb-ui-kit/issues/1505) (even though we are using an older one).
> Fixed weird bib btn behavior

- .github/workflows/deploy.yml
- _config.yml
- _includes/giscus.html
- _layouts/page.html
- _layouts/post.html
- _sass/_base.scss
- _sass/_distill.scss
giscus settings in `_config.yml` had al-folio repo specified by default. many users kept these defaults in their own repos, which resulted in getting comments from blog posts of different users posted to al-folio discussions. this is undesirable, since users lose control over the discussions in their blogs.
this PR solves the issue:
- first, we set `giscus.repo` to blank in `_config.yml`. if the field is kept blank, when the website is built locally, the user will see a warning saying that giscus comments are misconfigured.
- second, we add a step to the `deploy` workflow that writes repository name to `giscus.repo` in `_config.yml`. that way, even if `giscus.repo` field is left black or set to an incorrect repo, it gets correctly populated at deployment time.
other small changes in this …
> Update giscus setup via github action

- _config.yml
- _includes/scripts/badges.html
- _layouts/bib.html
fixes #1665 by adding `enable_publication_thumbnails` flag to config. if set to false, thumbnails are disabled across all publications and the layout is adjusted accordingly.
> Make publication thumbnails optional + fix small layout bugs

- _includes/latest_posts.html
- _includes/news.html
This is a quick fix of issue #1499. The widths of the date and the title are by default dynamically determined by their lengths. I manually set the width of date as 20% of the table's width, so the alignment can be consistent.
> fix inconsistent alignment for latest posts

- _layouts/distill.html
Towards https://github.com/alshedivat/al-folio/discussions/1374
The image zooming feature did not work with distill layout previously.
> ENH image zooming in distill posts

- README.md
Updated README to explicitly tell how to proceed on creating your own version based on this template. Also removed the video tutorial since it was for an older version, recommending to fork the repo and it was missing the `--lsi` parameter from jekyll command. Also was not using docker, the current recommended way.
> Updated README to explictly tell how to proceed on fresh install

- _includes/header.html
Apparently, submenus were not highlighted, even if the current page was a child of that submenu.
This patch checks, if the title of the current page matches with the title of a submenu child. If so, it sets the submenu and the corresponding child as active, highlighting it in the header.
> check for active children in submenus

- _config.yml
- _layouts/bib.html
When the video entry is added to bib:
e.g.,
```
{
...
video={https://www.youtube.com/embed/jNQXAC9IVRw}
...
}
```
A dedicated button appears for videos. When clicked, a playable video appears under the research article (like abstracts and bibtex)
> Added video button to bib entries

- _config.yml
After deploying my website (Cloudflare Pages), my Giscus did not work, I realized these two paramesters are removed. After adding them again, my Giscus worked correctly.
These new values are values from previous commits of original repository
> bring back `repo_id` and `category_id` in `giscus` section

- _config.yml
- _includes/figure.html
- _includes/projects.html
- _includes/projects_horizontal.html
- _layouts/about.html
- _layouts/bib.html
- _layouts/profiles.html
Fixes #1967 
Update the way responsive images are used to only use one srcset, and add corresponding `sizes` attribute to the relevant layouts and templates. 
I did not go through and add `sizes` to all the example posts/projects. When `sizes` is not specified by the user, the `figure.html` template defaults to 95% the width of the viewport which should work fine for most cases; users can optimize further if they wish by feeding `sizes` into the template.
Additionally:
- Enabled support for .gif to .webp compression
- fix error in jekyll-imagemagick config where all images were resized to be 800px or less. (for example img-1400.webp was actually only 800px wide, etc.)
- added note about making sure imagemagick is installed before enabling it in responsive images section of `_config.yml`
> Responsive image fix

- docker-compose.yml
Fix #2021 : The webpage hosted by docker would not be automatically reloaded because the port used for live-reloading (port 35729) is not forwarded.
> fix live-reloading in docker

- _config.yml
I had added -strip arg to the imagemagick call as it is generally desirable to strip metadata from images before publishing them, however it seems to occasionally cause issues with jekyll-imagemagick auto-regeneration, regenerating images even when they have not changed.
> Remove imagemagick strip

- _includes/selected_papers.html
- _layouts/page.html
- _layouts/post.html
- _pages/publications.md
- _posts/2023-07-12-post-bibliography.md
- _projects/1_project.md
Since the citation file and other stuff is already defined in `_config.yml`, removed them when calling `{% bibliography %}`. Also realized that `jekyll-scholar` helps in displaying only the papers cited in page, changed to use that.
> Added citation examples, simplified citation code

- _pages/404.md
- _pages/news.md
moves news and 404 from repo root dir to `_pages/` where they are supposed to be + changes their extensions to `.md`
> Move news and 404 to pages

- _posts/2023-05-12-custom-blockquotes.md
Fixed issue #2066. Removed `>` in front of `{: .block-tip }` which was introduced by prettier in the example post. Maybe add /_post/*.md into .prettierignore to prevent similar breaks in the future.
> Fix custom blockquotes

- .github/workflows/broken-links-site.yml
- .github/workflows/deploy.yml
- .github/workflows/prettier.yml
Added another GitHub action to check for broken local links on version of the site that will be deployed.
The `broken-links` action check for broken links considering documentation files (like INSTALLING.md) and also pages like [_pages/about.md](https://github.com/alshedivat/al-folio/blob/master/_pages/about.md), but it can't check for broken links when the link will be handled by jekyll tags (like in [_pages/blog.md](https://github.com/alshedivat/al-folio/blob/master/_pages/blog.md).
With `broken-links-site` we can check if all the links that will be used on the final site that refer to local files are correct. Focusing only on local files since this would end up calling too many checks for library files, like `https://unpkg.com/bootstrap-table@1.22.1/dist/bootstrap-table.min.css`.
> Link checks on deploy

- .github/workflows/prettier-on-pr.yml
- .github/workflows/prettier-on-push.yml
- .github/workflows/prettier.yml
Splitted prettier GitHub action into two:
- `on push`, only runs on direct pushes, if test fails generates an artifact (that lasts for 3 days) with an html version of the changes needed to pass prettier test
- `on PR`, only runs on PRs, if test fails comments on the PR with the HTML content of the diff
I couldn't actually test the `on PR` version since it needs to be on a PR in the master branch, so this will only be triggered after this PR is accepted, and for the next PR that fails prettier test.
PS: currently the artifact is a zip file with the html inside. It is not currently possible to generate it other way, we have to wait for [this issue](https://github.com/actions/upload-artifact/issues/14) to be closed.
> Prettier check now generates a diff comment on PR

- .github/workflows/lighthouse-badger.yml
- README.md
Added support for Lighthouse test as a GitHub action, and it appears like [this](https://github.com/george-gca/multi-language-al-folio?tab=readme-ov-file#lighthouse-pagespeed-insights). The only thing missing is for @alshedivat to create a [repository secret](https://github.com/MyActionWay/lighthouse-badger-workflows#lighthouse-badger-easyyml) named `LIGHTHOUSE_BADGER_TOKEN` with the information needed.
> Added Lighthouse test GitHub action

- _includes/head.liquid
- _includes/scripts/leaflet.liquid
- _layouts/default.liquid
- _posts/2024-01-26-geojson-map.md
- _sass/_base.scss
- assets/js/copy_code.js
Added support for GeoJSON maps.
> GeoJSON support

- _includes/scripts/vega.liquid
- _layouts/default.liquid
- _posts/2024-01-27-vega-lite.md
- assets/js/copy_code.js
- assets/js/theme.js
Added support for [vega lite](https://vega.github.io/vega-lite/) charts.
> Vega lite support

- _includes/head.liquid
- _includes/scripts/codeDiff.liquid
- _includes/scripts/misc.liquid
- _layouts/default.liquid
- _posts/2023-03-21-tables.md
- _posts/2024-01-27-code-diff.md
- assets/js/copy_code.js
- assets/js/theme.js
Added support to display diff code in a prettier way with [diff2html](https://diff2html.xyz/).
It displays code like [in this example](https://diff2html.xyz/demo.html).
> Support for diff2html

- _layouts/default.liquid
In reference to issue: https://github.com/alshedivat/al-folio/discussions/1818
Redirect cases were only happening on the surface level, essentially just affecting the links on [blog index](https://alshedivat.github.io/al-folio/blog/page/4/index.htm) and [year tag](https://alshedivat.github.io/al-folio/blog/2022/). However, from the actual [site](https://alshedivat.github.io/al-folio/blog/2022/redirect/), it would automatically redirect to the `base_url` rather than the actual `redirect`. 
In my update, if `redirect: true`, like it is in `404.md`, redirect behavior is the same, redirecting to the `base_url`. If it is an external link, then the redirect is external. And finally if it is an internal redirect, like it is in https://alshedivat.github.io/al-folio/blog/2022/redirect/, than the …
> improved redirect mapping

- _sass/_base.scss
This PR changes the footer text on the website (for both the sticky and fixed footer) to be centered by default. This change is based on the discussion post #257.
> center footer text by default

- _bibliography/papers.bib
- _config.yml
- _layouts/bib.liquid
- _plugins/google-scholar-citations.rb
Closes #1809, but there are caveats:
1 - it only works at build time, which means it won't update the numbers unless you build your site again
2 - Google might block the request if it receives lots of it, failing the whole process.
This is how it looks like when it can fetch the information:
And this when it fails:
> Added support for google scholar citations

- README.md
Adds [https://ericslyman.com/](https://ericslyman.com/) to the list of academic community examples.
> Add academic community example

- _includes/header.liquid
I removed the spaces between the first, middle and last names in the header.
It's just my preference, I don't know if it would be accepted but I have done this for my own page using this repository as a template.
> remove the space in names of "site"

- _config.yml
- _includes/figure.liquid
This PR introduces an enhancement to the site's image-loading strategy by implementing lazy loading as the default behavior for all images. The motivation behind this change is to improve the site's load times.
**Changes:**
1. **Default Lazy Loading:** By `default`, all images will now have the `loading="lazy"` attribute.
2. **Configurable Option in `_config.yml`:** Added a new configuration option under `lazy_loading_images.enable`.
3. **Override Capability:** For `specific images` where the user doesn't want lazy loading, they can `override` this by directly setting the `loading attribute` in the `image tag`.
> Implement Default Lazy Loading for Images with Configurable Option

- _includes/projects.liquid
- _includes/projects_horizontal.liquid
- _layouts/about.liquid
- _layouts/bib.liquid
- _layouts/profiles.liquid
- _posts/2015-05-15-images.md
- _posts/2024-01-27-advanced-images.md
- _projects/1_project.md
- _projects/2_project.md
- _projects/3_project.md
- _projects/4_project.md
- _projects/5_project.md
- _projects/6_project.md
Our score went down a little bit after the last few changes. Avoiding lazy loading some images (as introduced in #2183), since [it is strongly recommended to omit hero images and other images or iframes that are likely to appear above the fold from being lazy-loaded](https://web.dev/articles/browser-level-lazy-loading-for-cmss#avoid_lazy_loading_above-the-fold_elements). Also added missing `alt` to google scholar field.
> Lighthouse fixes

- _layouts/about.liquid
- _pages/about.md
I noticed disabling latest_posts in `_config.yml` didn't work because the variable in the liquid template was seemingly incorrect. This should fix that.
> Correct config variable for enabling latest_posts on about page

- _includes/scripts/mathjax.liquid
The PR replaces `polyfill.io` inside the template with `cdnjs.cloudflare.com/polyfill`.
---
`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.
[The original creator of the `polyfill.io` has voiced his concern on Twitter](https://twitter.com/triblondon/status/1761852117579427975). And since the acquisition, numerous issues have …
> Replace `polyfill.io`

- _layouts/archive-category.liquid
- _layouts/archive-tag.liquid
- _layouts/archive-year.liquid
- assets/js/no_defer.js
The blog archive page tables have `table-borderless`, but bootstrap-table JS adds `table-bordered` by default and this forces an `!important` border.
Since these tables are also supposed to be borderless, this PR excludes them from bootstrap-table, just like the news and CV table are.
> Remove bootstrap-table from archive tables

- _config.yml
- _includes/social.liquid
I added further social integration for:
1. ACM: https://dl.acm.org/profile/
2. IEEE: https://ieeexplore.ieee.org/author/
Given their importance in computer science, I would like to have them in al-folio.
> feat: added IEEE and ACM social

- _bibliography/papers.bib
- _config.yml
- _layouts/bib.liquid
- _sass/_base.scss
- _sass/_themes.scss
- assets/js/common.js
This PR adds an "award" button to publications.
It takes the `award` value from the bibtex entry and displays(incl. Markdown rendering) the text in a box similarly to abstract and bibtex.
User can set the entry `award_name` to configure the value. See example config with `award_name: Nobel Prize`.
The color of the award box can be configured in `_base.scss`.
Note, there is a similar PR #2175, it I saw to issues with:
1. There was no progress
2. The award button just prints the text directly in the button, similarly to `award_name`. Long award names could clutter the webpage.
3. IMHO, it brokes the current al-folio design, since butons do have a fixed size/text. However, variable prize names are also possible with this PR.
***
Pictures:
Default. Text are hidden:
Additional info is shown …
> Feature: added "award" for publications

- docker-compose-slim.yml
- docker-compose.yml
Fixes #2303.
See #2333 for discussion.
> Use JEKYLL_ENV=development in Docker Compose setup

- _bibliography/papers.bib
- _config.yml
- _layouts/bib.liquid
As discussed in #1181, I suggest to make embedding videos an optional feature.
This behavior aligns well with recently merged PR #2312.
Open questions:
1. I added a youtube link to `papers.bib`. Is this link okay?
2. I set `enable_video_embedding: false` as the default. I argue that privacy settings should be the default. Also, the current implementation of `video.liquid` only works for some very specific video URLs. For example, to embed youtube, specialized links must be used to avoid `X-Frame-Option` issues. This behavior can lead to a broken embedding, which would not look very nice.
Feedback welcome.
> feat: make video embeddings optional.

- _includes/resume/work.liquid
adding "location" element when location object is added to work experience. Location icon and the entered value will appear on the CV page under the work experience section. This feature already exists for education section, but not for work. The change is made to make the experiece more consistent.
> Update work.liquid to show the location of work experience under cv page

- _plugins/external-posts.rb
Adjusting issue #2343 by adding null check.
> adding null check to external-posts.rb to avoid parsing failure

- INSTALL.md
Fixing the docker command based on `docker compose [-f <arg>...] [options] [COMMAND] [ARGS...]` format on the [website](https://docs.docker.com/compose/reference/#command-options-overview-and-help).  
Because the old command would give error: `unknown shorthand flag: 'f' in -f`
> Fix docker compose command using the slimmed docker image

- _bibliography/papers.bib
- _data/venues.yml
- _layouts/bib.liquid
- _sass/_base.scss
This PR enables to have `abbr` and `preview` for a single publication (closing #1162).
The following example shows all three possibilities: 1) Preview + Abbr 2) Preview only 3) Abbr only.
> Feat bib preview (closes #1162)

- _includes/projects.liquid
- _includes/projects_horizontal.liquid
- _pages/blog.md
- _pages/projects.md
- _projects/1_project.md
- _projects/3_project.md
- _sass/_base.scss
The current state of project looks a bit unharmonized.
***
These improvements are not perfect, but to be honest, I have no deep experiences with bootstrap. Actually, I just read the [docs](https://getbootstrap.com/docs/4.4/components/card/) and tried my best. 
But I think it looks way better than before.
I'm pretty happy with the vertical layout, but the horizontal could be improved.
I tried various things to get a better alignment of the image, without any success.
In theroy, there is e.g. `card-img-top`, but I could not make it work.
I changed the project descriptions to make some of these edge-cases visible.
Feedback and improvements (especially code) are more than welcome
Closes #2246
> Feat reworked project layout (closing #2246)

- _plugins/download-3rd-party.rb
Added condition to avoid security issue according to GitHub's dependabot
> Fixed security issue with download 3rd party plugin

- _layouts/post.liquid
- _posts/2024-01-27-vega-lite.md
This PR is related to #2309. I added an optional `last_updated` field. This new field represents the timestamp for when the post was last updated. Consequently, the existing `date` metadata should now be interpreted as the creation date of the post. 
The formatting for displaying these dates has been standardized as follows:
```text
Created: July 11, 2023   |   Last Updated: April 14, 2024
```
For a practical implementation example, please refer to [this post](https://torydeng.github.io/blog/2023/deploying-server/) on my website, where I have applied these changes.
---
Any feedback is wellcome.
> add last updated date to posts

- _layouts/bib.liquid
- _sass/_base.scss
[Reference](https://github.com/alshedivat/al-folio/pull/2352#issuecomment-2067965077)
I'm not sure if the removal of `max-width: 90vw;` for all images causes any side issues.
I could at least not find any. But having this properties will produce unaligned preview sizes. 
Help/testing is more than welcome.
...
> Fix bib preview mobile

- _layouts/bib.liquid
This PR fixes a very niche bug.
If there is a co-author that is not *me* (=`<em>` tagged) and does not have a `coauthor_url` (=`<a>` tagged), there will be a leading whitespace before the separating comma. If the author list is split into multiple lines (due to long author lists or a small view), the whitespace can lead to a line beginning with a comma.
As I said, very niche, but interestingly, the other cases already did the same whitespace handling. Just the case not-me/no-url was mising.
Currently, we do not have this case on vanilla al-folio, but you can see it for example on [my website](https://christianmainka.de/publications/) if the view is small (e.g., 430px).
Related to #1502.
> fix(style): remove whitespace before comma

- Dockerfile
This PR should fix the issues reported in https://github.com/alshedivat/al-folio/issues/2384 , https://github.com/alshedivat/al-folio/issues/2392 and https://github.com/alshedivat/al-folio/issues/2395.
It seems that the ruby docker image is not affected by these problems.
> Fix docker image building

- _config.yml
- _includes/head.liquid
- _includes/scripts/chartjs.liquid
- _includes/scripts/imageLayouts.liquid
- _includes/scripts/leaflet.liquid
- _includes/scripts/mathjax.liquid
- _includes/scripts/pseudocode.liquid
- _includes/scripts/tikzjax.liquid
- _plugins/download-3rd-party.rb
Fixes #2419 by downloading leaflet images. Also changed the path where the libraries are downloaded to avoid not downloading files with same name.
> Fix offline leaflet

- README.md
Embedded System Lab @ Northeastern University (NU-ESL) website recently embraced Jekyll with al-folio theme. Add nuesl link to README.md
> Add NEU ESL to README.md

- _includes/scripts/search.liquid
Thank you @george-gca for the awesome work. on #2415.
This PR generalizes the search on all collections. Currently, only projects are added to the search.
This PR uses all of them, such as news. On my personal website, I use a teaching collection which is then also automatically searched.
> feat: search.liquid over all collections

- _config.yml
- _plugins/external-posts.rb
- updates `external-posts.rb` plugin, allowing the user to specify an explicit lists of urls in `_config.yml` that are then displayed in the blog feed as external posts
- 99% of the code in this change is written by gpt-4: https://chat.openai.com/share/24432d24-36a7-4d6f-a5c0-d7e5142f68cd
> Enable specifying explicit list of external posts to display

- .gitignore
- _sass/_base.scss
This PR fixes an issue where the search input is not visible in the light theme. This is because `ninja-header-min.js` defaults the text color to white. 
This style change will ensure that the text is always visible regardless of theme selection
> Bugfix: Updates ninja keys text input color so it is always visible

- _includes/scripts/search.liquid
This PR addresses #2438 by programmatically collapsing the navbar if the user clicks on search on mobile.
> Bugfix: Collapse the navbar on mobile when the user selects search

- _layouts/default.liquid
- assets/js/shortcut-key.js
This addresses issue #2437 by:
- Adding a new script that dynamically sets the search keyboard shortcut by checking what platform the user is currently using
- Loading this script in `default.liquid`
> Feature: Dynamically sets the search shortcut key based on the user's platform

- _includes/scripts/search.liquid
Fixes #2469. Separated `news` and `posts` from other collections in search, since it caused duplicated entries. Also to ensure they are in chronological reverse order.
> Fixes external blog posts in search

- _config.yml
- _posts/2023-05-12-custom-blockquotes.md
```
1. Go to `blog/`
2. Select "🏷️ Blockquotes" "search filter"
=> `blog/category/blockquotes/` returns 404
```
<hr>
1. Append 'blockquotes' to [`display_tags`](https://github.com/alshedivat/al-folio/pull/2480/files#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883R295)  
2. Replace 'blockquotes' with 'external-services' in `display_categories`  
=> Display 'blockquotes' tag and 'external-services' category on blog's front page
<br>
> [Tweak] Update "search filters" displayed on the blog's front page

- _includes/scripts/back_to_top.liquid
- _includes/scripts/diff2html.liquid
- _includes/scripts/echarts.liquid
- _includes/scripts/leaflet.liquid
- _includes/scripts/mermaid.liquid
- _includes/scripts/pseudocode.liquid
- _includes/scripts/search.liquid
- _includes/scripts/typograms.liquid
- _includes/scripts/vega.liquid
- assets/js/common.js
- assets/js/shortcut-key.js
For some unknown reason, all the `document.onreadystatechange = () => {` checks stopped working. Thankfully, replacing them with `document.addEventListener("readystatechange", () => {` fixed the issues.
> Fix code blocks not changing to plots and others

- _includes/pagination.liquid
Currently, on the [blog](https://alshedivat.github.io/al-folio/blog/) page, clicking "older" and "newer" on the pagination at the bottom direct you forward to links like `/al-folio/blog/page/2/` and backward to `/al-folio/blog/`. 
However, if you click on the `1`, `2`.. etc buttons, there is a different behavior. The links now contain an `index.html`. For example, clicking `2` leads you to `/al-folio/blog/page/2/index.html`. It is the same content, just with a messier hyper link. Same with clicking `1`, you are brought to `/al-folio/blog/`.
This fix creates a consistency among the hyper links in pagination.
> fix: remove 'index.html' in pagination

- _includes/header.liquid
Currently, in all blog posts, or any child page under /blog, the "blog" in nav is not highlighted. 
In all other child pages for a parent in nav, the parent is highlighted. For example, in a sub page of projects, projects in nav is highlighted. 
This fix creates a consistent behavior for nav and highlights the blog in nav if in a blog post.
BEFORE:
AFTER:
> fix: blog highlighted in nav for child pages

- CUSTOMIZE.md
- Gemfile
- Gemfile.lock
- README.md
- _config.yml
- _layouts/bib.liquid
- _plugins/hide-custom-bibtex.rb
- _sass/_base.scss
- assets/js/common.js
> Support superscripts in bibtex author names

- _config.yml
- _includes/footer.liquid
- _includes/header.liquid
- _includes/related_posts.liquid
- _includes/scripts/newsletter.liquid
- _layouts/about.liquid
- _sass/_base.scss
- _sass/_themes.scss
In reference to idea: https://github.com/alshedivat/al-folio/discussions/2097
In reference to request: https://github.com/alshedivat/al-folio/issues/923#issuecomment-2171924663
Added support to integrate a [loops.so](https://loops.so/) mailing list into the site.
To use, you need to enable `newsletter` in `_config.yml`. You also must specify a loops endpoint (although I think any mailing list endpoint can work), which you can get when you set up a mailing list on loops. More documentation on loops: [here](https://loops.so/docs/forms/custom-form).
Once that is enabled, the behavior is different depending on how you specified your footer to behave in `_config.yml`. If `footer_fixed: true`, then the sign up will appear at the bottom of the about page, as well as at the bottom of blog posts, …
> Added support for a newsletter

- _data/repositories.yml
- _includes/repository/repo.liquid
Hello! I had this minor issue on my website and I saw few other people using this template and having the same issue.
**Brief**
if two repo's in the same row has different number of lines for the descriptions, heights of the cards will not be the same if we don't force the number of lines to be displayed.
**Solution**
By looking at [This issue](https://github.com/anuraghazra/github-readme-stats/issues/2900) I could see that they solved it by adding an new option, `description_lines_count`. This was used on the API request in order to fix the issue.
---
---
> Fix repo card heigth for different repo descriptions

- _config.yml
- _includes/scripts/misc.liquid
- _pages/publications.md
- _sass/_base.scss
- assets/js/bibsearch.js
- assets/js/highlight-search-term.js
This PR adds a simple filter/search functionality to the bibliography.
It can be used in two ways:
1. Simply enter a search term in the input box.
2. Send a search term via the `location.hash`, e.g., https://alshedivat.github.io/al-folio/publications/#mechanics
**Notes:**
- The search box is optional. It can be simply removed if anyone does not like it.
- Searching via `hash` works without the search box. My idea is to use this functionality to index all BibTeX entries via the `ctrl-k` search and link them via their BibTeX key.
- Searching via `hash` could also be used to set static links on the current page, e.g., to filter specific co-authors, venues, etc.
- I don't know much about the design of the input field. I simply reused the newsletter box style.
- Entering a search term in the …
> feat: simple filtering / searching on bibliography

- _layouts/bib.liquid
These somehow appeared when upgrading from v0.11.0 to v0.12.0.
> Fix space before some bib commas

- _config.yml
- _layouts/bib.liquid
Currently Altmetric and Dimension publication badge elements have non-obvious attributes that hide badges when some conditions are not met ,e.g.:
```
data-hide-no-mentions="true"
data-hide-less-than="15"
```
resulting in seemingly strange behavior where badges are enabled in `config.yml` but don't show up consistently, as reported in #2443 : Altmetric badges don't display for some pubs.
- removes these hidden nondisplay conditions in favor of more predictable website behavior;
- adds documentation links to point users interested in customizing badge behavior to the right resources.
> Make publication badges always visible

- _includes/bib_search.liquid
- _includes/scripts/misc.liquid
- _pages/publications.md
In #2523, I did a copy&paste error with https://github.com/alshedivat/al-folio/commit/07d6e619cced7a2256bbe6de582ad68f93cd1553
I used the global `search_enabled` config key instead of the correct `bib_search` key.
This PR fixed it.
> fix: search_enabled -> bib_search

- .github/workflows/lighthouse-badger.yml
- CUSTOMIZE.md
- INSTALL.md
In the [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md#my-webpage-works-locally-but-after-deploying-it-is-not-displayed-correctly-css-and-js-are-not-loaded-properly-how-do-i-fix-that), it is mentioned to "add it as a secret". However, the Lighthouse Badger documentation specifies using an environment variable. I've updated this to use secrets instead, as it is more secure and appropriate for using a Personal Access Token (PAT).
- **contents**: access: read and write
- **metadata**: access: read-only
- **repo**
[refer](https://github.com/MyActionWay/lighthouse-badger-workflows#lighthouse-badger-easyyml:~:text=and%20permissions%20required-,PAT%20(fine%2Dgrained)%3A%20repository%20permissions,-contents%20%3D%3E%20access%3A%20read)
For more information, refer to the [GitHub …
> Lighthouse Badger token as secret

- _posts/2023-03-21-tables.md
- _sass/_base.scss
Default, meaning `pretty_table: false`
```md
|   First Column   |  Second Column  |  Third Column  |
|------------------|-----------------|----------------|
| Sed in.          | Sed non.        | Morbi egestas. |
| Donec facilisis. | Suspendisse eu. | Nulla porta.   |
| Praesent a.      | Interdum et.    | Sed nec.       |
```
> [bug-fix] Add padding to default markdown table cells

- _sass/_base.scss
Currently, the tip, warning, and danger custom blockquote's font color is not customized when the text is styled as bold, italics, or a list item. As a result, the text is slightly less attractive in light mode and almost illegible in dark mode.
> [Bug-fix] Make custom blockquote font coloring consistent

- README.md
- _bibliography/papers.bib
- _config.yml
- _includes/social.liquid
- _layouts/bib.liquid
- _plugins/inspirehep-citations.rb
[INSPIRE](http://inspirehep.net/) is a trusted community hub that facilitates the sharing and discovery of accurate scholarly information in high energy physics. By integrating the social and citation count badge, al-folio users within this community will gain significant benefits.
In continuation of #2634, I am creating this pull request.
- Add your INSPIRE author ID in the `config.yml` under `inspirehep_id`.
- Enable this feature by setting `inspirehep` to `true` under `enable_publication_badges` in your `config.yml` file.
- In your bibliography file (e.g., `papers.bib`), add `inspirehep_id = {the literature's recid}` under the citation of a literature source.
> [Feature] InspireHEP social and citation count badge

- _pages/repositories.md
Inverted order of title and {% if site.data.repositories.github_users %}, so that if there is no github_users, the "GitHub users" title does not appear.
> Fix no github_users titling in repositories.md

- .github/workflows/prettier-html.yml
The GitHub Workflow formats the html files on gh-pages. The html files generated are always on a single line. This makes scaling programs a lot more difficult. By formatting the HTML files, al-folio can now be used to generate code which can then be modified to allow for using back-end.
I want to let you know that when I was using prettier for this, it kept crashing and after some debugging I found out that al-folio was generating an invalid tag ```</source>```. ```<source>``` is a self-closing tag and doesn't have a separate closing tag.
Error: ```<source src="URL" type="type"></source>```
Correct: ```<source src="URL" type="type">```
1. The workflow starts by checking out the gh-pages branch.
2. Then it finds all ```</source>``` tags in all html files and deletes them.
3. It Installs …
> Added gh-pages Formatter

- _pages/blog.md
This PR fixes an issue where unnecessary horizontal lines were displayed when there were no tags or categories present. The tag and category container is now conditionally rendered, ensuring it only appears when there are tags or categories to display.
no tags meaning, in _config.yml
```
display_tags: []
display_categories: []
```
The difference is illustrated in the images below:
- **First Image (Fixed)**: Shows the correct behavior with no extra lines when tags or categories are absent.
- **Second Image (Current)**: Demonstrates the issue with unwanted horizontal lines appearing when no tags or categories are present.
This change improves the visual consistency and cleanliness of the theme by preventing unnecessary elements from being rendered, particularly in cases where there are no …
> Fix conditional rendering of tag and category section

- _includes/figure.liquid
Added a default srcset in case extension is other than the following:
- .jpg
- .jpeg
- .png
- .tiff
- .gif
fixed #2660
> Fixed .webp src creation for svg and other files

- _includes/figure.liquid
This PR allows the `figure` to accept url as the src of the`<img>`. currently, it only supports the relative path.
```
// raw img
// assign url to figure                 
{% assign image_url = image.url %}
{% include figure.liquid url=image_url class="img-fluid rounded z-depth-1" zoomable=true %}
```
> feature: figure support url.

- _config.yml
If `download: true`, the site deployment fails.
This caused e.g. issue #2548.
I believe the issue appears because the 3rd party downloaded libs rely on ES6 Syntax, which jekyll-minifier cannot work on correctly.
Also, I think we do not need to minify 3rd party downloaded libs at all.
While this PR does **not** fix the issue above, it at least ensures that the site can be deployed with `download: true`. We still need better ES6 support as suggested in #2571.
> fix: do not included downloaded assets in jekyll-minifier

- Dockerfile
Hello,
This pr should address the issue where the equations in jupter notebooks were not being rendered correctly in issue https://github.com/alshedivat/al-folio/issues/2757 .
> update dockerfile to render jupyter notebook equations

- _includes/figure.liquid
This PR addresses an issue with the filter for creating `.webp` srcsets introduced in PR #2698. The original filter incorrectly searched for extensions with a leading period (e.g., ".jpg" and ".png"). As a result, no matches were found, preventing the srcset from being added to any figures. This occurred because the split operation removes the period from the file extensions.
- Updated the filter to search for file extensions without the leading period (e.g., "jpg" and "png").
- Ensured that the resource sets are now correctly created for the respective file extensions, allowing the `.webp` srcset to function as intended.
With this change, responsive images will now correctly generate their srcsets for the appropriate file types, improving image loading performance and supporting better …
> Fix .webp SrcSet Creation Filter

- docker-compose.yml
This is to address 
- #2733 
Since a lot of times, the only problem is that docker image is not consistent with the build. We have to somehow incorporate image version into repository. 
I don't insist to provide it this way. Maybe there are other automatic ways which are better. 
We can also calculate the relevant tag from git.
> Add Image Version to Docker-Compose to pull the relevant image

- _includes/pagination.liquid
- _sass/_base.scss
I tested on my Github page and it worked correctly. Then, copied here. 
Issue: Blog page navigation extends layout of the page in small screens.
Fixes: #2841
> [FIX] Blog Page Navigation (#2841)

- _config.yml
- _includes/social.liquid
This PR modifies
- `_config.yml` to rename `bluesky_url` into `bluesky_id`
- `_includes/social.liquid` to handle the renaming in the display of social media icons
> Bluesky URL prefix should not be appended

- .github/workflows/broken-links.yml
- .lycheeignore
Add a .lycheeignore file with LinkedIn to stop the error in the workflow Link Checker due to response 999, and update to the new version lycheeverse/lychee-action@v2.1.0.
> Add .lycheeignore file with linkedin to stop error on workflow Linkcheck

- _layouts/cv.liquid
- _pages/cv.md
> Support for Resume/CV Links

- CUSTOMIZE.md
- INSTALL.md
Update CUSTOMIZE.md to include steps to deploy al-folio on Netlify.
> Update the INSTALL.md file to include steps for deploying al-folio on Netlify.

- _layouts/distill.liquid
- _posts/2018-12-22-distill.md
- package-lock.json
While using the distill template, I noticed it lacked many features available in the regular post template, such as typograms, echarts, and other interactive elements. To address this, I **included the necessary scripts and dependencies for these features in** _distill.liquid_, referencing them from misc.liquid. Now, the distill template offers the same interactive functionality as the post template.
> Add features to distill template

- _includes/repository/repo.liquid
- _includes/repository/repo_trophies.liquid
- _includes/repository/repo_user.liquid
- _sass/_themes.scss
Closes #930.
We already had classes for this kind of feature, but it was used specifically for repository information. Just renamed the classes so it is clear how they can be used.
To use them with markdown, just do it like this:
```markdown
```
and with html:
```html
<img
class="only-light"
src="assets/img/prof_pic_color.png"
>
<img
class="only-dark"
src="assets/img/prof_pic.jpg"
>
```
> Renamed `repo-img-` to `only-` to allow setting images for only one theme

- _includes/social.liquid
Fixes #2890 
With the recent updates (v0.13.0) the email badge (social) does not contain the email anymore.
Some link generations in social.liquid used the old schema
Also updated the handling for mastodon to be aligned to the other social badges.
> Update social.liquid: ensure social[1] is used

- .github/workflows/axe.yml
- .github/workflows/broken-links-site.yml
- .github/workflows/deploy.yml
Install `imagemagick` within `Install and Build 🔧` step of Github actions
Relevant issue: 
[#2902](https://github.com/alshedivat/al-folio/issues/2902) `convert` Command Not Found on Ubuntu 24.04
Reason: 
`ubuntu-latest` in Github actions is pointed to `ubuntu-24.04` now, in which `imagemagick` is no longer pre-installed. See [this](https://github.com/actions/runner-images/issues/10772).
Modified files (actions) recommended by @george-gca 
```
- .github/workflows/deploy.yml
- .github/workflows/broken-links-site.yml
- .github/workflows/axe.yml
```
> explicitly install imagemagick to support ubuntu-latest (>=24.04) in Github actions

- _sass/_cv.scss
PR #2617 added a noticeable amount of right padding to all table cells. This might be fine for tables in content (e.g. posts), but creates odd spaces in the CV page, which is largely made up of tables.
> Revert padding from #2617 for CV tables

- .gitattibutes
Shell scripts like entry_point.sh caused errors in Docker due to CRLF line endings on Windows (`exec /tmp/entry_point.sh: no such file or directory`).
Added `.gitattributes` to enforce LF line endings for *.sh files.
This resolves the issue and ensures consistent behavior across platforms.
> Fix Line Ending Issues for Shell Scripts in Docker for Windows 10

- CUSTOMIZE.md
- _layouts/about.liquid
- _layouts/post.liquid
> Howto remove pages

- FAQ.md
Added documentation for Google Search Console ID creation and usage in the template for google-site-verification.
> Updated FAQ.md.

- _layouts/cv.liquid
Hi,
I noticed an issue where the CV page fails to link to the correct custom PDF when the `{% unless site.data.resume %}` block is executed in `cv.liquid`. To resolve this, I updated the code to align its logic with the else block to make it consistent.
> Fix resume custom reference link bug

- assets/js/mathjax-setup.js
When dark mode is enabled, inline math expressions rendered using `$...$` in distill-style blog posts are displayed in black text. This makes them difficult to read against the dark background. The issue occurs because the default styles for MathJax-rendered content do not account for dark mode and set the text color to black.
This PR updates the MathJax setup to dynamically apply inline styles to ensure the text color of MathJax-rendered content inherits the parent container’s color. Specifically:
- Added a custom action in the _MathJax.options.renderActions_ section to inject a CSS rule that sets _.mjx-container_ to inherit its color from its parent element.
- Ensures that inline math expressions render correctly in both light and dark modes without explicitly setting a fixed color. …
> Fix issue causing no color inversion when rendering equations

- _plugins/external-posts.rb
This should fix several issues with indexing external posts, including #1828.
In short, I found that the issue with indexing was that the index builder was receiving 'empty' documents. To fix that, I'm setting the document content to be the post content as retrieved from the rss feed or the text extracted from the external page.
I've tested with various blog sources and it seems to be working as expected now.
> fixed indexing of external posts

- CUSTOMIZE.md
- _config.yml
- _includes/distill_scripts.liquid
- _includes/latest_posts.liquid
- _includes/news.liquid
- _layouts/about.liquid
- _pages/about.md
Moved news and latest posts related information from `_config.yml` to `_about.md` page.
> Moved specific information from config to about

- _includes/repository/repo.liquid
- _includes/repository/repo_user.liquid
The author of github-readme-stats uses the non-standard code "cn" for simplified Chinese, see [here](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#available-locales). While for traditional Chinese the author only provides "zh-tw". The github-readme-stats functions on repo page will break if the user sets the site language to ALL variants of Chinese except for zh-tw. This hack is to make all sub-variants of simplified Chinese fall back to "cn" and all sub-variants of traditional Chinese fall back to "zh-tw".
This patch fixes the problem and has been tested locally & with GitHub pages.
> fix language-not-found issues on repo page with simplified and traditional Chinese

- _config.yml
Resolve #3037
This PR just re-enable the old exclusions of jekyll-minifier to ensure that the files aren't altered.
> Re-Enable exclusions of jekyll minifier

- _config.yml
- _scripts/search.liquid.js
Earlier there was a tag in the `_config.yml` file to exclude the posts from the search results. I could no longer find that option and hence modified the `search.liquid.js` file.
It basically checks if the `posts_in_search` tag is true or not.
> Re-add ability to exclude posts from search

- _layouts/bib.liquid
When formatting the list of authors of a paper, there is a comma and the word 'and' before the last author. With 3 or more authors this can be interpreted as Oxford comma, but with two authors it is just wrong.
I applied this patch locally to get rid of the last comma.
Before:
After:
> Fix "comma and and" before last author in publication list

- _data/socials.yml
- _includes/social.liquid
This pull request adds support for Academia.edu profiles to the al-folio social media integrations. Academia.edu is widely used by academics to share and discover research,.
The changes are minimal and well-contained:
1. Added configuration options in socials.yml for Academia.edu with organization and username fields
2. Updated social.liquid to handle the new social integration using the Academicons font which already includes support for Academia.edu
The implementation uses Academicons, which already includes the Academia.edu icon (`ai-academia`), making this addition a natural fit for the theme.
Unlike some other social media links that only require a single ID or URL, Academia.edu profiles include both an organization (subdomain) and a username in the format: …
> Add Academia.edu support to social media integrations

- _config.yml
- _includes/giscus.liquid
- _scripts/giscus-setup.js
Currently, the `site.giscus.theme` option is ignored because `giscus.liquid` always computes the theme as light/dark based on the current site theme. This PR allows users to configure separate light and dark giscus themes in `_config.yml`, which will support dynamic updates when switching between light, dark, or system themes.
Fixes #3269
> Make Giscus light and dark themes configurable via _config.yml

- _includes/social.liquid
Partially addresses issue #3280.
Currently, the RSS feed icon in the socials section will show whenever `rss_icon` in `data/_socials.yml` has a value --- **even if that value is `false`**.
Unlike the other social settings, which are empty by default, for `rss_icon` the default setting is `true`.
So it makes sense that a user might expect `rss_icon: false` to disable said icon.
This PR just adds a check if the value is `false` and hides the icon if so.
> Socials icons: Check if rss_icon: false
