_config.yml
_includes/social.html

Can be seen in action here: https://spd.gr/

Add social buttons: Publons, ResearchGate and Blogger

---

_includes/hemline.html

Thanks for sharing this work. I just started using it for g-oikonomou.github.io
This pull makes the inclusion of google analytics conditional.

Make google analytics conditional

---

_config.yml
_includes/footer.html
_includes/head.html
_includes/header.html
_layouts/about.html

OK well that was faster than expected.
Example rendering now
closes #110 
closes #109

FIX add first/middle/last name var in config

---

.gitignore
Gemfile
_config.yml
_posts/2020-09-28-twitter.md

* Feature Request : https://github.com/alshedivat/al-folio/issues/85
* Created sample blog post for tweet card examples.
* Added twitter plugin dependency : https://github.com/rob-murray/jekyll-twitter-plugin
* Added .tweet-cache/ to .gitignore.
* https://jongwoo-shim.github.io/al-folio/blog/2020/twitter/

Added Twitter Card Support

---

Gemfile
_config.yml
_posts/2020-09-28-github-metadata.md

* Feature Request : https://github.com/alshedivat/al-folio/issues/85
* Added github-metadata dependency :  https://github.com/jekyll/github-metadata
* Created sample blog quickly going over Github MetaData.
* https://jongwoo-shim.github.io/al-folio/blog/2020/github-metadata/

Github MetaData

---

_includes/scripts/misc.html

GA site tag was updated today, misc.html has been changed to reflect the same.
Please test on your site.
On my site this change worked smoothly.

Updated Google Analytics code

---

README.md

add one website to list of academics

---

_config.yml
_includes/social.html

This commit allows to add keybase social url.

Add keybase badge

---

_sass/_base.scss

Description text size should match whether or not there is a link.

Update _base.scss for the `post-description` style.

---

README.md

`$theme-color` value should be updated from `_sass/_themes.scss` instead of `_sass/variables.scss`

Update README, change $theme-color in _themes.scss

---

_config.yml
_sass/_variables.scss
assets/css/main.scss

add wide screen configuration by adding a `max_width` config in `_config.yml` 
possibly related issue #143

add wide screen configuration

---

README.md

Hi developers,
This theme is awesome! Can we add my personal homepage to the "academics" examples? Thanks

Adding my personal site to academic pages

---

.github/workflows/deploy.yml
_config.yml
_includes/social.html
bin/deploy

Allow email to be empty - for spam protection and add entry for work homepage.

social: add work url

---

README.md
_config.yml
_includes/head.html

Minor commits:
1. Adding my webpage to the list of academic pages
2. Adding panelbear analytics option. Changes to the config file (analytics id entry, enable entry). Script added to head.html.

Add webpage + add panelbear analytics

---

_includes/header.html
_sass/_base.scss

* Changed color of icon from static to using variable.
* Minor typo fix.
* Can be checked on https://jongwoo-shim.github.io/al-folio/
* Tested using both phone and web-dev mode.

Issue 173 fix

---

README.md

CMU Distributed Systems systems course

Add community listing

---

_layouts/distill.html

fix distill pubiblication date

---

_config.yml
_includes/social.html

Add gitlab to social

---

README.md

Changed "For personal and organization webpages" part, tried to be as concise as possible, in accordance with: https://github.com/alshedivat/al-folio/issues/209#issuecomment-798849211

Added proper instructions in personal webpages

---

_includes/social.html

Pretty self-explanatory I guess.
Many thanks for the awesome theme!

add dblp to social links

---

_bibliography/papers.bib
_layouts/bib.html

Added BibTeX hidden block as described in issue #146.
Credits go to @AbeHandler.

Added BibTeX hidden block

---

_sass/_base.scss

Fix project page colors

---

_config.yml
_includes/head.html
_includes/scripts/misc.html
_posts/2015-05-15-images.md
_posts/2020-09-28-twitter.md
_sass/_base.scss
assets/js/zoom.js

Adds support for image zoom

---

_pages/projects.md

Fixes #304. Fix bad horizontal template include

---

_includes/head.html
blog/index.html

Fix the blog page title

---

Gemfile
README.md
_config.yml

Initial Atom (RSS-like) feed support

---

_posts/2015-05-15-images.md
assets/js/dark_mode.js
assets/js/theme.js
assets/js/zoom.js

When switching between light and dark mode, this PR correctly updates background overlay of the zoomed images.

Correctly update medium-zoom background when switching theme

---

_config.yml

https://github.com/alshedivat/al-folio/pull/270#issuecomment-874912253

_config.yml: add dblp_url

---

_includes/head.html

Reverts alshedivat/al-folio#234

Revert "Change gitcdn link in "

---

_config.yml
_includes/social.html

pull request for issue #406 
This is also working perfectly on my own [website](https://pourmand1376.github.io/).

Add stackoverflow icon in social page

---

404.html
_layouts/default.html

A minimal 404 page which redirects to the main page.
Issue: #395

Add 404.html

---

_includes/responsive_img.html

Reverts alshedivat/al-folio#451
Fixes #467.

Revert "remove extra space in profile image path"

---

_config.yml
_includes/head.html
_includes/social.html
_layouts/about.html
_layouts/default.html

Some minor changes to improve the [lighthouse score](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Falshedivat.github.io%2Fal-folio%2F).

Lighthouse enhancements

---

_layouts/distill.html
_posts/2018-12-22-distill.md
_sass/_distill.scss
_sass/_layout.scss
assets/css/main.scss

Add TOC to distill template

---

README.md

My personal [website](https://niweera.gq) uses this template. I updated the README.md file as instructed.

Add a website to list of Academics websites

---

_layouts/distill.html
_posts/2018-12-22-distill.md

Correctly slugify distill TOC

---

_config.yml
_includes/head.html
_includes/scripts/bootstrap.html
_includes/scripts/jquery.html
_includes/scripts/mansory.html
_includes/scripts/masonry.html
_layouts/default.html

Also, update the links to jsdelivr CDN, as they are more efficient in my experience.

Update library versions (bootstap, jquery, fontawesome, academicicons, masonry, mdbootstrap)

---

README.md

Hey guys! I've been using your theme for 2 years now and only just got around to figuring out how to make a pull request to add myself to your examples in the readme file. Keep up the great work! I reccomend your theme to almost everyone!

added my website to readme examples

---

README.md

Hello! Just adding my website to your list -- thanks so much for making this theme! :)

Add my personal website to Readme examples

---

README.md

Figured I'd add my own website here as the Readme suggested

Add my own site to the readme

---

_layouts/default.html

The problem is easily solved by adding some space. #553

Layout Spacing problem when footer_fixed: false

---

_includes/news.html

Fix a small bug in news

---

README.md

Hi, 
Greetings from Kun Wu. This is a really awesome template! Very handy and impeccable styling.
This PR adds a star hyperlink to my website.
Thank you!
Best Regards,
Kun

Add K-Wu's Personal Website as a Star in Readme

---

README.md

Thank you for the amazing resource. I had a great time creating my personal website using al-folio.

Added amalawilson.com to the list of user samples

---

_sass/_base.scss

Fixes #620.
|Before|After|
|-|-|
|<img width="800" alt="Screen Shot 2022-04-03 at 8 54 17 AM" src="https://user-images.githubusercontent.com/2126561/161429106-61564271-b3d0-4611-9fb1-cc792f1e51fd.png">|<img width="800" alt="Screen Shot 2022-04-03 at 8 54 37 AM" src="https://user-images.githubusercontent.com/2126561/161429110-b2516fbd-6521-4d76-a0f8-aa4d31de3dbc.png">|

Fix table colors in dark mode

---

.github/workflows/deploy.yml

fixes #208.
the fix is as suggested in https://github.com/alshedivat/al-folio/issues/208#issuecomment-1053417425.

Call bash on bin/deploy in github actions

---

README.md

Add a start to list of academic personal webpages

Add a new star

---

README.md
_config.yml
_includes/figure.html
_includes/header.html
_includes/scripts/bootstrap.html
_includes/scripts/misc.html
_layouts/distill.html
_sass/_base.scss

A bunch of small changes and fixes:
1. Some lighthouse fixes 
2. A couple of speed improvements
3. Updated the README
4. Added a config option `enable_responsive_images` for disabling responsive images (issue #537)
5. Fixed git rebase statement in README (#692)
6. Updated the distill layout (better management of scripts)

Minor changes and fixes

---

_layouts/about.html
_pages/about.md

Support for cicular image

---

_config.yml
_includes/figure.html

Related to: https://github.com/alshedivat/al-folio/discussions/543#discussioncomment-3105602

Change imagemagick optional to one variable

---

.github/workflows/deploy.yml

References:
1. https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
2. https://github.com/ruby/setup-ruby#caching-bundle-install-automatically

Better bundler caching for GitHub Actions

---

_includes/scripts/bootstrap.html
assets/js/common.js

- Fix bootstrap script loading
- Fix removed waves effect from mdb bootstrap

Fix scripts

---

.github/workflows/deploy-image.yml

Skip Docker Image on Forked Repos

---

README.md

Great template! It took no time, I also added multilingual support very easily

Add personal page

---

README.md

Add a page

---

_layouts/about.html
_pages/about.md

Changed "cicular" to "circular"

Fix typos of about page circular p.p.

---

README.md

Added a link to my personal website to the README

Add dominikstrb's personal page

---

_layouts/bib.html

Aims to fix: https://github.com/alshedivat/al-folio/issues/912

fix bug where proceedings do not render

---

README.md

I added a few docker badges to show docker pull count, docker image size, and the latest docker image version.

Add docker badges

---

_config.yml
_includes/social.html

I opened an issue   https://github.com/alshedivat/al-folio/issues/973, but got it to work faster than I imagined

Added Mastodon to social

---

README.md

Added a link to my personal website to the README.

Add Junshen's personal page

---

README.md

Thanks a lot for this very neat and professional template. This PR adds my academic page to the Academics list

Add Andreas Kuster's published webpage

---

bin/deploy

Fixes #820.
Explanation: https://github.com/alshedivat/al-folio/discussions/969#discussioncomment-4180959

fix deploy script for `--user`

---

docker-compose.yml
docker-local.yml

This commit adds a container name for docker for more readability.

Add Container Name

---

_layouts/bib.html

1. Use the nicer layout for thesis entries in bib layout by supporting the `school` field.
2. Add support for the `note` field.
3. Fix proceedings type lookup split.
4. Add space between journal/book/school and year if both present.

Improve bib layout for thesis

---

README.md

adding my website to the list of academics using al-folio; thanks for the terrific Jekyll theme!

add star to readme

---

_config.yml
_includes/social.html

Add youtube as a social option

---

_config.yml
assets/js/zoom.js

Fix medium zoom on small devices

---

_config.yml

Sorry, forgot to change the SRI.

Fix SRI hash

---

README.md
_bibliography/papers.bib
_config.yml
_includes/scripts/badges.html
_layouts/bib.html
_layouts/default.html
_sass/_base.scss

This adds a dimension badge as requested in #987.
This separates the the links from the badges, in case more badges need to be added in the future.

Adds Dimensions badge

---

_config.yml

fix: small typo

---

README.md

Adding my portfolio website to the list.

Add star to academic portfolios

---

README.md

Added new academic site
Signed-off-by: George Araújo <george.gcac@gmail.com>

Added george-gca academic site

---

404.html

Fixing in accordance to https://webaccess.berkeley.edu/ask-pecan/click-here
Also relates to https://github.com/alshedivat/al-folio/discussions/1188

Update 404.html wording for accessibility

---

_config.yml
_includes/metadata.html
_includes/social.html

I imagine more people have wikipedia accounts than wikidata entries about them 😉

feat: add wikipedia social

---

_includes/social.html

Added missing "/" in the OSF link.

OSF social link

---

README.md

By using this Github action it is possible to keep the derived repository up-to-date with its template.
I am currently using this to keep my website up to date with the template repository. An example of the PR this action creates can be seen [here](https://github.com/george-gca/george-gca.github.io/pull/13).

Added information about using github action

---

README.md

Update README.md: added new profile

---

README.md

Update README - Add new profile

---

Gemfile
_config.yml
_layouts/post.html
_posts/2023-03-20-table-of-contents.md

Added support for table of contents in blog posts

---

README.md

Added my own website to the "stars" section

added one more researcher

---

_sass/_base.scss
assets/js/copy_code.js

Fix issue #1303 by adding a code wrapper outside the code block. 
Ref: https://stackoverflow.com/questions/60771472/position-a-button-such-that-it-wont-scroll-with-contents

Fix copy code button position

---

_includes/latest_posts.html
_includes/news.html

Fixed size of news and latest posts in about page when visualizing in mobile.

Increased allowed max size of news and latest posts in about

---

_sass/_base.scss

Fixed bug when using latex in title and description

---

_includes/head.html
_includes/scripts/misc.html
_layouts/default.html
_layouts/post.html
_posts/2023-04-25-sidebar-table-of-contents.md
_sass/_base.scss
assets/js/common.js

Toc sidebar

---

_sass/_base.scss

Fixed color and increased font size of toc sidebar

Toc sidebar color fix

---

README.md

Add an academic example 

---

_posts/2015-05-15-images.md
blog/index.html

Implemented #425 based on given code.

Added thumbnail support for blog posts

---

_sass/_base.scss

Fixed bootstrap table css that is being overwritten by mdb css

Fixed bootstrap table css

---

README.md

Hello, I'd appreciate it if you could consider including my academic personal webpage as an example. Thank you.

add academic personal webpage example

---

README.md

Hi al-folio maintainer, kindly add my site as an academic example.

add star to academic examples

---

README.md

Please add a star for my personal website. Thank you!

Added star for samadamday.com in the README

---

README.md

We would gladly appreciate it if fanpu.io and abigalekim.github.io can be added as examples to the README  of personal page stars!

Update README personal page stars

---

README.md

Added the following examples:
* A personal homepage
* A workshop website

Added two more examples

---

.github/workflows/deploy-image.yml

I added multi-architecture support for docker images. 
- #1469 
ToDo:

Update Docker Images to support M1 Mac

---

.github/workflows/pagespeed.yml
README.md

Created GitHub action to update site pagespeed svg

---

README.md

Added anmspro.github.io in academics

Added anmspro.github.io in academics

---

_includes/metadata.html

Changed metadata info for when page is a blog post.

Added metadata info when blog post

---

_config.yml
_includes/social.html

Solving #1569 
I added Zotero socials because I needed them; opened a issue/pull request in case I'm not the only one.
Second  pull request (previous: #1570 ) because unwanted commits retroactively crept in somehow. It was easier to force reset (which closed the pull request automatically apparently).

Added Zotero socials

---

_layouts/page.html
_projects/2_project.md

Solves #1586 by adding the option for giscus comments sites using the pages layout and minimally modifies Project 2 to show giscus comments as an example

Al folio main giscus pages

---

_includes/figure.html

figure.html was incorrectly setting height=max-height instead of max-height=max-height

incorrect max-height in figure.html

---

README.md

Added academic website to README.md.
Also added `_blank` target to earlier ones.

Add star to README.md

---

README.md

Added academic website to README.md.

Add a star

---

_config.yml
_includes/scripts/wechatModal.html
_includes/social.html
_layouts/default.html
_sass/_base.scss

When the WeChat icon in socials is clicked, a picture of your WeChat QR code is shown in the center of the screen. The actual picture of your QR code has to be uploaded.  Related to #1724

add WeChat to socials

---

README.md

Adding https://kudhru.github.io/ in the academics section

Adding a page (*) in README.md

---

README.md

- My [personal page](https://www.zhivotenko.com) as Senior Software Engineer and Senior Materials Scientist.

Added a star

---

_layouts/profiles.html
_pages/profiles.md

Added support for description in profiles page

Added description to profiles page

---

_pages/about.md
_pages/about_einstein.md

Update Font Awesome url

---

_layouts/post.html

Removed link to blog when showing years in news

Fixes #1584

---

_includes/head.html
_posts/2023-12-12-tikzjax.md

Implemented support for tikzjax

---

_layouts/archive-category.html
_layouts/archive-tag.html
_layouts/archive-year.html

Fixed redirect post access from blog archive

---

_sass/_base.scss

Ensure the zoomed image is in front of toc sidebar

---

blog/index.html

Just added a few lines of code so that the blog works with pagination off. It displays all posts - a zoomed out image is shown below.
Cheers!

added ability to switch off pagination

---

README.md

Added new user to academics section in readme. 
Thank you for this great resource!

Added additional user to README.md

---

README.md

Adding star

---

.github/workflows/axe.yml
.github/workflows/broken-links-site.yml
.github/workflows/broken-links.yml
.github/workflows/deploy-docker-tag.yml
.github/workflows/deploy-image.yml
.github/workflows/deploy.yml
.github/workflows/docker-slim.yml
.github/workflows/prettier.yml
INSTALL.md
_config.yml
purgecss.config.js

The GitHub actions were running everytime a new commit was made to the repo, but that wasn't needed. For example, we don't need to try to create a new docker image if the libraries didn't change, same to build the whole site after a change in the README.md.

Changed conditions of running GitHub actions

---

README.md

Added my own website as a star to the "Academics" section

Added one more researcher using al-folio

---

README.md
_includes/scripts/chart.liquid
_layouts/default.liquid
_posts/2024-01-26-chartjs.md
assets/js/copy_code.js

Added support for Chart.js

---

_config.yml
_includes/head.liquid
_includes/metadata.liquid
_includes/scripts/chartjs.liquid
_includes/scripts/diff2html.liquid
_includes/scripts/echarts.liquid
_includes/scripts/imageLayouts.liquid
_includes/scripts/leaflet.liquid
_includes/scripts/masonry.liquid
_includes/scripts/mermaid.liquid
_includes/scripts/tikzjax.liquid
_includes/scripts/vega.liquid
_layouts/default.liquid
_posts/2023-07-04-jupyter-notebook.md

Moved libs versions and hashes to `_config.yml`.
Fixes #2067.
Deferring everything possible to keep pages loads fast.

Move libs versions to config

---

assets/js/common.js

Fixed related publications appearing in toc

---

.github/workflows/broken-links.yml

See: https://github.com/alshedivat/al-folio/discussions/2366
See: https://github.com/lycheeverse/lychee/issues/1411

Set user agent for lychee

---

README.md

I've added my al-folio themed website link to the README's Academic websites section.

Added website link to README, Academics

---

_layouts/post.liquid

It seems the same problem exists in the posts as well. The relevant PR is [here](https://github.com/alshedivat/al-folio/pull/2444).

Delete extra space ; Update post.liquid

---

README.md

Hi, I would be more than happy if I could add my personal website here.

Added SRaf.ir to README.md

---

_includes/scripts/search.liquid

Fixed external post symbol on search

---

CUSTOMIZE.md

In reference to https://github.com/alshedivat/al-folio/pull/2517 and https://github.com/alshedivat/al-folio/pull/2517#issuecomment-2179244937

Update CUSTOMIZE.md for Newsletter support

---

_layouts/distill.liquid

Fixes issue #2554: search function is out of order in a distill style post.

Fix search in Distill style post

---

_includes/scripts/search.liquid

Fixed title search and truncating if larger than 13 words

---

README.md

I used al-folio's fork [multi-language-al-folio](https://github.com/george-gca/multi-language-al-folio) to create my portfolio, I love it :)

Alon Kellner portfolio link

---

_config.yml

Added the google_scholar_id to filtered keywords

Update _config.yml to add a filtered bibtex keyword

---

README.md

Hi, thanks for the great theme! Added my personal academic webpage to the community list.

Add my webpage to community list

---

README.md

Thanks for the amazing theme! ❤️ I've been using al-folio for several years, during which I have considered migrating to more modern technologies like MDX or similar but really found no theme that look better than this.

Added my portfolio website to README

---

_layouts/page.liquid

Support `_styles` in page layout as in post and distill

---

README.md

Adding a star to link to my website, as a user of the al-folio theme.

Add my website to the "Academics" list

---

Dockerfile
bin/entry_point.sh
docker-compose.yml

Fixed the `docker compose` issue, when trying to run the repository, locally.
#2795 
<hr>
<h3>To test these out: </h3>
Run:
`docker compose pull`
`docker compose build`
`docker compose up`

Fix docker compose issue

---

_includes/scripts/wechatModal.liquid

fix: Misfunction of wechat_qr in Social Integration

---

_includes/header.liquid

Page permalink can be an outside url

---

_config.yml
_includes/head.liquid
_includes/scripts/imageLayouts.liquid
_posts/2024-12-04-photo-gallery.md

Added support for multiple image galleries, and created a sample post showing how to enable and use them.

New image components (image galleries)

---

_layouts/bib.liquid

Fix site.data.socials.scholar_userid access for google scholar citation count
Fixes #2889

Update bib.liquid: google scholar citation count

---

README.md

Update README.md - remove my website link

---

_includes/related_posts.liquid

Fix related external posts

---

_includes/footer.liquid

Refactor footer content into a reusable variable for cleaner code

Refactor footer content

---

_includes/figure.liquid
_layouts/bib.liquid

Fix zoom in bibliography images

---

CUSTOMIZE.md

`excludes` should be `exclude`. `excludes` with `s` does not work with `_config.yml`, which itself uses `exclude` and `include`.

Fix typo in CUSTOMIZE.md

---

README.md

Love the theme and just used it for my own personal website! Thought I'd link from here as suggested in the README to show my support! :)

Add link to a new academic's website

---

README.md

Thank you for this slick theme! I've added my customized page to the community examples section. My implementation includes a few subtle tweaks that might inspire others, just as I found inspiration from existing community examples.

Added my website to the community pages.

---

README.md

Hi!
I’m using the al-folio theme for my academic homepage and really appreciate the work you’ve done — it’s clean, elegant, and super helpful.
I’ve added my site (https://d-jiao.github.io) to the community list as suggested. Thank you for maintaining this great project!
Best,
Dian Jiao (d-jiao)

added my homepage (Dian Jiao).

---

_config.yml
_data/socials.yml

Also make document clearer for rss_icon.

Remove unnecessary rss_icon line from _config.yml

---

_data/socials.yml
_includes/metadata.liquid
_includes/social.liquid
_scripts/search.liquid.js

Add HAL id to socials
